import type { Page, Product, Order, Coupon } from "@/lib/types";

export type View = { pageId: string; at: string };
export type Click = { pageId: string; href: string; at: string };
export type Subscriber = { pageId: string; email: string; at: string };

export type DbSeed = {
  pages: Page[];
  products: Product[];
  orders: Order[];
  coupons: Coupon[];
  views: View[];
  clicks: Click[];
  subscribers: Subscriber[];
};

export const defaultSeed: DbSeed = {
  pages: [
    {
      id: "page_demo",
      slug: "demo",
      name: "Rian Pratama",
      bio: "Software Engineer & Content Creator di Jakarta. Berbagi tutorial Next.js, AI workflows, template Notion, dan merchandise resmi komunitas.",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
      bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
      socials: {
        instagram: "rian.dev",
        youtube: "@rianpratama",
        github: "rianpratama",
        twitter: "rianpratama",
        whatsapp: "081234567890",
      },
      theme: "default",
      accentColor: "#2563eb",
      darkMode: false,
      isPublic: true,
      createdAt: "2026-09-29T09:52:32.262Z",
      updatedAt: "2026-09-29T15:20:00.000Z",
      bento: [
        {
          id: "b_h_store",
          type: "header",
          title: "Toko & Produk Digital",
          subtitle: "Dapatkan buku panduan, template kerja, dan preset pilihan",
          size: "4x1",
          pos: { x: 0, y: 0 },
        },
        {
          id: "b_countdown",
          type: "countdown",
          title: "Flash Sale Ramadhan 50%",
          targetDate: "2026-10-31T23:59:59.000Z",
          emoji: "⚡",
          size: "2x1",
          pos: { x: 0, y: 1 },
        },
        {
          id: "b_music",
          type: "music",
          title: "Lofi Chill Coding Playlist",
          url: "https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT",
          size: "2x1",
          pos: { x: 2, y: 1 },
        },
        {
          id: "b_prod_1",
          type: "product",
          productId: "prod_ebook",
          pos: { x: 0, y: 2 },
        },
        {
          id: "b_prod_2",
          type: "product",
          productId: "prod_notion",
          pos: { x: 0, y: 5 },
        },
        {
          id: "b_h_media",
          type: "header",
          title: "Video & Catatan Builder",
          subtitle: "Tutorial coding, arsitektur sistem, dan catatan pengalaman",
          size: "4x1",
          pos: { x: 0, y: 8 },
        },
        {
          id: "b_video",
          type: "video",
          title: "Tutorial Fullstack Next.js 16 & AI",
          url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          size: "2x2",
          pos: { x: 0, y: 9 },
        },
        {
          id: "b_note",
          type: "note",
          title: "Fokus & Update Q4 2026",
          text: "Halo teman-teman! Di kuartal ini saya sedang fokus mengembangkan template open-source baru dan kurikulum AI Agentic Coding. Semua pembeli produk digital otomatis mendapatkan akses private Discord dan update berkala gratis.",
          size: "2x2",
          pos: { x: 2, y: 9 },
        },
        {
          id: "b_h_collab",
          type: "header",
          title: "Studio & Kolaborasi",
          subtitle: "Kunjungi studio kami atau kirimkan penawaran kerja sama",
          size: "4x1",
          pos: { x: 0, y: 11 },
        },
        {
          id: "b_map",
          type: "map",
          label: "Rian Studio & Coffee Space",
          address: "Senopati No. 45, Kebayoran Baru, Jakarta Selatan",
          size: "2x2",
          pos: { x: 0, y: 12 },
        },
        {
          id: "b_note_contact",
          type: "note",
          title: "Jam Operasional & Kontak",
          text: "Buka: Senin - Jumat (10.00 - 18.00 WIB)\n\nUntuk sponsorship, pembicara seminar, atau konsultasi arsitektur teknologi, silakan kontak melalui email partner@rianpratama.id atau DM Instagram.",
          size: "2x2",
          pos: { x: 2, y: 12 },
        },
      ],
    },
  ],
  products: [
    {
      id: "prod_ebook",
      pageId: "page_demo",
      name: "Mastering Next.js 16 & AI SDK (Ebook PDF)",
      description: "Buku panduan praktis 180+ halaman untuk membangun aplikasi SaaS modern, integrasi payment gateway Midtrans, dan AI SDK dari nol.",
      priceIdr: 99000,
      originalPriceIdr: 149000,
      stock: 100,
      kind: "digital",
      imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      fileUrl: "https://raw.githubusercontent.com/example/demo.pdf",
      isActive: true,
      createdAt: "2026-09-29T09:52:32.268Z",
    },
    {
      id: "prod_notion",
      pageId: "page_demo",
      name: "Creator OS 2026 — Notion Workspace",
      description: "Sistem manajemen konten terpadu untuk kreator: editorial calendar, finance tracking, rate card, dan sponsorship pipeline.",
      priceIdr: 49000,
      originalPriceIdr: 89000,
      stock: null,
      kind: "digital",
      imageUrl: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=600&q=80",
      fileUrl: "https://notion.so/templates/creator-os",
      isActive: true,
      createdAt: "2026-09-29T13:07:31.316Z",
    },
    {
      id: "prod_preset",
      pageId: "page_demo",
      name: "Lightroom Preset Pack — Urban Jakarta",
      description: "Koleksi 12 preset Lightroom sinematik untuk street & night photography khas Jakarta.",
      priceIdr: 35000,
      originalPriceIdr: 59000,
      stock: null,
      kind: "digital",
      imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80",
      isActive: true,
      createdAt: "2026-09-29T14:00:00.000Z",
    },
    {
      id: "prod_merch_tee",
      pageId: "page_demo",
      name: "Preset Lightroom & LUT Cinematic Pack",
      description: "15+ preset tone warna cinematic untuk foto & video Instagram Reels/TikTok. Kompatibel dengan Lightroom Mobile & Desktop.",
      priceIdr: 49000,
      originalPriceIdr: 99000,
      stock: null,
      kind: "digital",
      imageUrl: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=600&q=80",
      fileUrl: "https://raw.githubusercontent.com/example/presets.zip",
      isActive: true,
      createdAt: "2026-09-29T14:10:00.000Z",
    },
  ],
  orders: [],
  coupons: [
    {
      id: "coupon_demo_hemat",
      pageId: "page_demo",
      code: "HEMAT20",
      discountType: "percent",
      discountValue: 20,
      minOrderIdr: 0,
      maxUses: 100,
      usedCount: 0,
      isActive: true,
      expiresAt: null,
      createdAt: "2026-09-30T10:00:00.000Z",
    },
    {
      id: "coupon_demo_berkah",
      pageId: "page_demo",
      code: "BERKAH30K",
      discountType: "fixed",
      discountValue: 30000,
      minOrderIdr: 50000,
      maxUses: 50,
      usedCount: 0,
      isActive: true,
      expiresAt: null,
      createdAt: "2026-09-30T10:00:00.000Z",
    },
  ],
  views: [],
  clicks: [],
  subscribers: [],
};
